name: My First Workflow

on: [push]

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout Repo
        uses: Actions/Checkout@v5

      - name: Checking the Code
        run: ls -l 
      
